### ISSUE TITLE
A single sort algorithm should be used for both Search and while browsing the Catalog

### ISSUE THREAD

**Issue by serenamarie125** [openshift/origin-web-catalog#171]
Results displayed in the search should be have the same sort order as items shown while browsing the catalog.  Currently, Search takes case into consideration, while browsing the catalog does not.  Would be great to have a single sort algorithm used by both!

<img width="1012" alt="screen shot 2017-04-21 at 3 38 26 pm" src="https://cloud.githubusercontent.com/assets/12504403/25293426/deef1776-26a8-11e7-9db1-9785a3304cfb.png">

**Comment by serenamarie125** [comment]
Will assign to David Cabrera once he is added to the OpenShift org ... he will be taking this one!

**Comment by serenamarie125** [comment]
per @jwforres, currently use native javascript localeCompare everywhere  (S -> t -> T)

It is possible there are places where we are sorting based on the unique name but showing a display name and so it looks like its a weird order.  We should fix those to sort by what we are displaying if we find any of those.  Sort in that case should sort by what we display first, if it sees two display names that are the same it should then compare their unique names as a secondary sort to make sure the sort is stable.

**Comment by spadgett** [comment]
Unique name is only unique per kind, and we're showing different kinds in the list. So we'll need to fallback to kind, too. Here is what we're doing now for categories:

https://github.com/openshift/origin-web-catalog/blob/1c1c0e3fcb1b21e8eea3df007f2b5981c1ee941c/src/components/services-view/services-view.controller.ts#L118-L122

We should move this to an AngularJS service so it can be reused and fix the display name to pass a compare fn that uses `localCompare`. Unique name and kind don't necessarily need `localeCompare` since they're only Latin characters, but display name does.

**Comment by spadgett** [comment]
This might be at least partially addressed by #164

**Comment by dtaylor113** [comment]
Hi, #164 does move the sort into a central AngularJS service which Search and Browsing use.  

However, it does not address:
> fix the display name to pass a compare fn that uses localeCompare. Unique name and kind don't necessarily need localeCompare since they're only Latin characters, but display name does.

@spadgett, can you point me to a code snippet which does this localeCompare?  -thanks

**Comment by dtaylor113** [comment]
Fixed via #164.  Opening up another issue to track the localCompare ask
