### ISSUE TITLE
When sorting Catalog Items, use localeCompare for Display Name

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-catalog#174]
Here is how we are sorting category items:

https://github.com/openshift/origin-web-catalog/blob/master/src/services/catalog.service.ts#L58

Fix the display name to pass a compare fn that uses localeCompare. Unique name and kind don't necessarily need localeCompare since they're only Latin characters, but display name does.

**Comment by spadgett** [comment]
We should also use `{ sensitivity: 'base' }` with `localeCompare` rather than `toLowerCase`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

@jwforres We should start using `localeCompare` for display names generally in the web console. It doesn't look like lodash uses it in `sortBy`.

**Comment by cdcabrera** [comment]
Closed with #191
