### ISSUE TITLE
Services matching subcategories appear when parent category doesn't match

### ISSUE THREAD

**Issue by cfchase** [openshift/origin-web-catalog#192]
When a subcategory matches, it's displayed even, if there's no match for the parent category:

For Example:
Given categories:
```javascript
var categories: any = [
  {id: 'amazon', label: 'Amazon' , subCategories: [
    {id: 'database', label: 'Database'}
  ]},
  {id: 'other', label: 'Other' , subCategories: [
    {id: 'other', label: 'Other'}
  ]}
];
```
and services with the following (abbreviated) json

```json
{
  "metadata": {
    "name": "amazon-database"
  },
  "osbTags": [
    "amazon",
    "database"
  ]
},
{
  "metadata": {
    "name": "plain-database"
  },
  "osbTags": [
    "database"
  ]
}
```

The plain database, not associated with Amazon, will show up under Amazon -> Databases.  I would have thought the parent tag must also be on the service for it to be included under that main category and sub category.

It may also occur that if the parent tag was different, ie parent-not-amazon, it might also show under Amazon, but I haven't tested it.

**Comment by dtaylor113** [comment]
Currently, osbTags are matched on sub-categories, which then pull in the parent category.   osbTags are also matched to the first sub-category found, which may not be optimal if, for example, there is Amazon -> Database, and say NodeJS -> Database, if an item just has an osbTag of 'database' it will match the first one found (probably Amazon->Database).
Also, osbTags are matched individually, ie there is no coordination with sibling osbTags.
There is also a related issue #29

**Comment by dtaylor113** [comment]
@spadgett , should all osbTabs be considered when matching to sub-category & category?  Can assume a parent-child ordering within the osbTabs (ie. ['amazon', 'database']), where leftmost are ancestors of rightmost?

**Comment by jwforres** [comment]
Things not appearing in multiple subcategories is a bug.  But I think @cfchase is making a good argument that only matching subcategories is probably not the right behavior even in our existing Browse catalog" experience (the old catalog).

The right approach is probably:
1) Items should be able to appear in multiple subcategories
2) Items should be matched into a subcategory if the id (or an alias) for the main category is in the item's tags AND the id (or an alias) for the subcategory is in the item's tags
3) We should NOT make any assumptions about ordering of tags

So looking at our builder images as an example, they all have both "builder" and then a language tag like "java".  We should make "builder" an alias for the "Languages" top level category, that is a reasonable assumption for us to make.

We will probably need to look closely at our OOTB templates in combination with this new behavior and make sure things can still fall into all the areas we expect.  We need to go through this effort anyway I think to make sure the OOTB categorization is correct for the templates that get installed with oc cluster up / ansible.

**Comment by jwforres** [comment]
I think we will probably hit an issue with some of the quickstart templates not falling into the Languages subcategories like we want them to. I doubt we have a common set of tags across those templates that we could match to a top level category.

**Comment by dtaylor113** [comment]
Hi @jwforres, you wrote:

> Items should be able to appear in multiple subcategories

Currently items would appear in multiple subcategories if they have multiple tags associated with different subcategories.  Ex.  If an item had osbTags of: "ruby, mysql", it would appear under Languages->Ruby and Databases->mySQL.

> Items should be matched into a subcategory if the id (or an alias) for the main category is in the item's tags AND the id (or an alias) for the subcategory is in the item's tags

Sounds reasonable, although for the example above the osbTags would have to be "builder, ruby, databases, mysql"  -the osbTabs would have to have main and sub category tags in order to be categorized properly. 

> We should NOT make any assumptions about ordering of tags

Agree

**Comment by jwforres** [comment]
On Mon, May 1, 2017 at 12:38 PM, David Taylor <notifications@github.com>
wrote:

> Hi @jwforres <https://github.com/jwforres>, you wrote:
>
> Items should be able to appear in multiple subcategories
>
> Currently items would appear in multiple subcategories if they have
> multiple tags associated with different subcategories. Ex. If an item had
> osbTags of: "ruby, mysql", it would appear under Languages->Ruby and
> Databases->mySQL.
>
It should not require having different tags.

**Comment by dtaylor113** [comment]
> It should not require having different tags.

Ah...you are saying if one tag, say 'mysql' exists under 'Amazon' and 'Databases', the item should appear under both main categories.

**Comment by jwforres** [comment]
On Mon, May 1, 2017 at 1:37 PM, David Taylor <notifications@github.com>
wrote:

> It should not require having different tags.
>
> Ah...you are saying if one tag, say 'mysql' exists under 'Amazon' and
> 'Databases', the item should appear under both main categories.
>

Yes and no. That is the primary concern, but I'm also saying if someone
wants to define multiple subcategories under the same main category that
have the same tag, then more power to them. That's their choice, we have no
reason to stop them, we have no reason to make assumptions about "which one
wins".

**Comment by dtaylor113** [comment]
Here is my first initial attempt to define the correct categorization algorithm: 

![image](https://cloud.githubusercontent.com/assets/12733153/25590168/5e14e2ca-2e7d-11e7-9742-98b25a72466f.png)

**Comment by jwforres** [comment]
ok @spadgett and I discussed this and there is a way to do this that gives us all the support / flexibility we need.

The key is to make matching of main categories optional.  Every main category can choose to define a tag that will be matched against. I would iterate over main categories first instead of subcategories, if a main category has a matcher tag then check if the item matches it, if not then continue to the next main category, if so then figure out which sub-categories it should be placed into, if there are none then put it into that main category's Other sub-category.  If a main category does NOT have a matcher tag then the item will be placed into any matching subcategories, if there are no matching subcategories then the item is not included underneath that main category at all.  As part of this process you just need to track was an item placed into *any* sub-category (including a main category's Other), and if not, then it gets put into the top level Other.

I think this means the "id" of the main category needs to not be the thing we match against, we need a separate optional field like "tag".

**Comment by dtaylor113** [comment]
Ok, so given the categories:
```javascript
var categories: any = [
  {id: 'amazon', label: 'Amazon' , tag: 'amazon', subCategories: [
    {id: 'database', label: 'Database'}
  ]},
  {id: 'databases', label: 'Databases', subCategories: [
    {id: 'database', label: 'Database'}
  ]},

];
```
and services with the following (abbreviated) json

```json
{
  "metadata": {
    "name": "amazon-database"
  },
  "osbTags": [
    "amazon",
    "database"
  ]
},
{
  "metadata": {
    "name": "amazon-widget"
  },
  "osbTags": [
    "amazon",
    "widget"
  ]
},
{
  "metadata": {
    "name": "plain-database"
  },
  "osbTags": [
    "database"
  ]
},
{
  "metadata": {
    "name": "foobar"
  },
  "osbTags": [
    "foobar"
  ]
}
```
The following categorization would be:
```
Amazon
  Database
    amazon-database
  Other
    amazon-widget
Databases
  Database
     amazon-database
     plain-database
Other
  foobar    
```

**Comment by jwforres** [comment]
Yes.  I'm wondering two things about the category definitions though, should we:

1) make "tag" on main categories be "tags" instead and have it be an array of strings, so people can match more than one tag (we allow this today on subcategories for our old catalog)
2) for subcategories should we have an explicit "tags" for consistency instead of checking for "id" + "aliases", but in the case of subcategories "tags" must exist and be non-empty

**Comment by spadgett** [comment]
@jwforres agree on both (1) and (2)

**Comment by dtaylor113** [comment]
> for subcategories should we have an explicit "tags" for consistency instead of checking for "id" + "aliases",

I agree on both as well.  Does this mean "tags" will replace "categoryAliases" in sub-categories?

**Comment by jwforres** [comment]
On Tue, May 2, 2017 at 9:15 AM, David Taylor <notifications@github.com>
wrote:

> for subcategories should we have an explicit "tags" for consistency
> instead of checking for "id" + "aliases",
>
> I agree on both as well. Does this mean "tags" will replace
> "categoryAliases" in sub-categories?
>

Yeah
