### ISSUE TITLE
Search doesn't match category display names

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#197]
Related to #192, but since the items don't need tags that match the ID of the parent, searching on the parent ID or display name doesn't show any results. I'd expect items under "CI/CD" to display when I search for "ci"

<img width="984" alt="screen shot 2017-05-02 at 8 03 47 am" src="https://cloud.githubusercontent.com/assets/1167259/25617012/0a5ef7f6-2f0e-11e7-905f-fcbefc3fb3fa.png">

cc @jwforres @dtaylor113

**Comment by jwforres** [comment]
We should consider this as part of https://trello.com/c/2fFSJMX1 since even with the updated categorization its optional whether there is a parent tag that has to be matched.  Things that match because they are under a parent category that matches the text are definitely lower in search results priority to things that directly match on their own.

I'm going to close the issue since its now tracked in the trello card for future work.
