### ISSUE TITLE
Horizontal form labels with no whitespace are overflowing on the inputs

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#250]
![label-overflow](https://cloud.githubusercontent.com/assets/1467629/26451684/13c59172-412b-11e7-9615-2cca2c330724.png)

**Comment by spadgett** [comment]
Likely a problem for both the order-service component in origin-web-catalog and the process-template component in origin-web-console.

**Comment by rhamilto** [comment]
I think we need to revisit the decision to use a [horizontal form](http://getbootstrap.com/css/#forms-horizontal) as we've got wrapping issues at small (≥768px), medium (≥992px), and large (≥1200px) grid sizes.  Given the fact that template labels can be crazy strings like the ones in this bug, I think this is the only way to sensibly fix the problem.  The obvious downside is the forms will get longer.  Thoughts @jwforres, @spadgett, @sg00dwin?

768px no wrap
![768px no wrap](https://cloud.githubusercontent.com/assets/895728/26454067/ea553cd0-4133-11e7-9a6d-a60fea52a0cb.png)

768px wrap
![768 wrap](https://cloud.githubusercontent.com/assets/895728/26454089/fa25933a-4133-11e7-868a-2266e3e6d577.png)

992px no wrap
![992px no wrap](https://cloud.githubusercontent.com/assets/895728/26454104/0b1ebdce-4134-11e7-8379-f03822da476a.png)

992px wrap
![992px wrap](https://cloud.githubusercontent.com/assets/895728/26454159/3488b868-4134-11e7-9f0d-b36aa94d1760.png)

1200px no wrap
![1200px wrap](https://cloud.githubusercontent.com/assets/895728/26454313/c52c9222-4134-11e7-97b5-9412dc210af2.png)

1200px wrap
![1200px wrap](https://cloud.githubusercontent.com/assets/895728/26454338/d15e32b2-4134-11e7-9b18-a28576c90e7d.png)

**Comment by sg00dwin** [comment]
I agree with Rob, switching this to be vertically presented label & input pairs would be much better.

**Comment by serenamarie125** [comment]
@openshift/team-ux-review FYI

Looking at the link you provided @rhamilto the horizontal form seems to respond nicely responsively.  Is there a reason we can't do this?

<img width="879" alt="screen shot 2017-05-25 at 12 09 48 pm" src="https://cloud.githubusercontent.com/assets/12504403/26459052/3110d1c0-4143-11e7-8dd1-f9df1edd7309.png">

<img width="726" alt="screen shot 2017-05-25 at 12 09 40 pm" src="https://cloud.githubusercontent.com/assets/12504403/26459049/2eebc21a-4143-11e7-9320-47fee1730923.png">

**Comment by rhamilto** [comment]
> Looking at the link you provided @rhamilto the horizontal form seems to respond nicely responsively. Is there a reason we can't do this, or is that what you are saying :)

The horizontal form is problematic because:

1.  Our forms can have very long, unbroken strings as labels.  As template labels are defined by the template authors, we have no control over them.  It is common practice within templates to use labels like the ones shown in the example (e.g., OPENSHIFT_OAUTH_PROVIDER_URL).
2.  We're putting the form in a much more horizontally constrained area than the Bootstrap example.

**Comment by jwforres** [comment]
In the example screenshots above they handled it by completely dropping the labels and assuming the placeholder text in the inputs were the same as the labels, which to me is an odd redundancy in the first screenshot to begin with. We actually can't make that assumption because one of the common extensions to JSON schema lets you specify placeholder text for parameters, a broker may choose to provide a short hint as placeholder text.

**Comment by rhamilto** [comment]
That second screenshot is actually an [inline form](http://getbootstrap.com/css/#forms-inline) and not a [horizontal form](http://getbootstrap.com/css/#forms-horizontal).  The content jumps when the viewport is resized.

**Comment by ncameronbritt** [comment]
The forms will obviously get longer by moving the labels above the fields, but that effect would be mitigated somewhat because the hints underneath would be able to go full width. That would save some vertical space.

**Comment by rhamilto** [comment]
> The forms will obviously get longer by moving the labels above the fields, but that effect would be mitigated somewhat because the hints underneath would be able to go full width. That would save some vertical space.

To @ncameronbritt's point, here is the same form with labels on top.  We no longer have the wrapping issue, and the form is marginally taller because the help text is full width.

![screen shot 2017-05-25 at 1 29 05 pm](https://cloud.githubusercontent.com/assets/895728/26462388/8e00b232-414e-11e7-9894-c18d2bdd92f6.PNG)
![screen shot 2017-05-25 at 1 29 20 pm](https://cloud.githubusercontent.com/assets/895728/26462390/8e02fbc8-414e-11e7-8835-85b1c691e3b2.PNG)
![screen shot 2017-05-25 at 1 29 39 pm](https://cloud.githubusercontent.com/assets/895728/26462389/8e016e2a-414e-11e7-957c-9d19d64023e1.PNG)

**Comment by ncameronbritt** [comment]
That looks cleaner to my eye because we don't have that ragged left edge anymore.

**Comment by serenamarie125** [comment]
So let's remember that for 3.7, this will become a single column panel, so there will be more room.  I don't think we should change it now, just to change it again in a number of weeks.

**Comment by serenamarie125** [comment]
oops you are right @rhamilto labels move above rather than inside.

So the responsive behavior is to do what you are suggesting as the default @rhamilto 

I still think that having labels right aligned on the same row should be the default for a number of reasons:
- takes less vertical real estate
- makes sense for when this ordering panel becomes a single column and we will have more width to display

Can we adjust responsively and place them above?

**Comment by rhamilto** [comment]
> So let's remember that for 3.7, this will become a single column panel, so there will be more room. I don't think we should change it now, just to change it again in a number of weeks.

This is a bug in 3.6.  If we don't fix it now, QE will open a bug, and we'll still have to fix it.

> Can we adjust responsively and place them above?

That's how it works now (the breakpoint is 768px).    We could up that breakpoint, but the problem persists even at a 1200px wide viewport as shown in the screenshots.

**Comment by beanh66** [comment]
@rhamilto I agree, this change makes sense for now. We will likely have to change the label format back next release though once it's a single panel form, but as long as we are okay with that.

**Comment by serenamarie125** [comment]
+1 to having it a temporary fix for 3.6 :)  

Thanks @rhamilto
