### ISSUE TITLE
Need to address terminology inconsistencies in the binding step for ordering

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-catalog#279]
Binding from the overview in the console probably has same issues.

**Comment by jwforres** [comment]
cc @serenamarie125

**Comment by jeff-phillips-18** [comment]
Adding an application to a project:
![bind_add_application](https://user-images.githubusercontent.com/11633780/27341614-c9231ef6-55ab-11e7-9c98-78190d482e4e.png)

Binding an application in a project:
![bind_existing_applicaton](https://user-images.githubusercontent.com/11633780/27341625-d0eb76ec-55ab-11e7-9255-aa6ebb6144bc.png)

Adding a service to a project:
![bind_add_service](https://user-images.githubusercontent.com/11633780/27341631-d488695e-55ab-11e7-91f1-17f11fc8a4f4.png)

Binding a service in a project:
![bind_existing_service](https://user-images.githubusercontent.com/11633780/27341645-dd69c0b8-55ab-11e7-8715-5640c9c9a945.png)

Bind in progress:
![bind_progress](https://user-images.githubusercontent.com/11633780/27341660-e46b8f54-55ab-11e7-8364-5ff25d05fe1e.png)

**Comment by serenamarie125** [comment]
Here are updated wording changes.  Please note that there is a method to my madness with the strategy of using a "."

![orderservice-binding](https://user-images.githubusercontent.com/12504403/27404449-1e7f2d36-569c-11e7-801e-22e7d4ff96bb.png)
![application-createbinding](https://user-images.githubusercontent.com/12504403/27404448-1e7eca6c-569c-11e7-8543-872f345b1977.png)
![service-createbinding](https://user-images.githubusercontent.com/12504403/27404450-1e7f95c8-569c-11e7-84d6-5439f21d32c9.png)
![ordertemplate-binding](https://user-images.githubusercontent.com/12504403/27404451-1e833732-569c-11e7-95d5-5850c50a14d8.png)

@ncameronbritt FYI since this changes some of your original Bind designs
@jwforres this is the final wording proposal
@jeff-phillips-18 I think it's ready to go!

**Comment by ncameronbritt** [comment]
Nice! I think this is much clearer. 

One comment: "Inject" sounds more technical than most of the text. Is that a concept our users would understand, or is there another way to phrase it? "Create a secret and provide it to an application"?

**Comment by spadgett** [comment]
@serenamarie125 Looks much better than what we have 👍 

In the last wizard, Node.js is your application, not a service, so I don't think the suggestion is quite right. We might want to change Node.js there to the name that you picked your app also.
