### ISSUE TITLE
Page feels empty when no filters match

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-catalog#461]
@openshift/team-ux-review Should we have a blank state message or something below the filters saying there are no matches?

cc @dtaylor113 @jeff-phillips-18 

![openshift catalog components 2017-10-02 13-48-06](https://user-images.githubusercontent.com/1167259/31091292-7321b214-a778-11e7-979c-82d1426fb79f.png)

**Comment by beanh66** [comment]
@spadgett Yes, good catch I definitely agree! @jhaines any thoughts from a visual standpoint? Curious if we already do this elsewhere in PatternFly.

**Comment by beanh66** [comment]
How about something like this? 
![empty-catalog](https://user-images.githubusercontent.com/18057044/31189392-1f13ccfe-a906-11e7-827f-1ffab28bee6c.png)

**Comment by ncameronbritt** [comment]
Here are PF's guidelines, they're very similar to what @beanh66 proposed:
http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design

**Comment by dtaylor113** [comment]
Hi @amarie401,

Please review the angular-patternfly pfListView's [example](https://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfListView#example_demo) and how we use the '[ ] Items Available' checkbox to hide/show the [pfEmptyState](https://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfEmptyState) component.  Particularly, the HTML display logic [here](https://github.com/patternfly/angular-patternfly/blob/master/src/views/listview/list-view.html#L75)

Keep in mind our angular-patternfly view examples with the 'empty state' show when there are no items to begin with (as opposed to all of them being filtered out).  I think we can use the pfEmptyState component to also show an appropriate message and 'Clear Filters' link when there are no items due to an applied filter returning no results.

The end goal is we'll need to update the catalog code [here](https://github.com/openshift/origin-web-catalog/blob/master/src/components/services-view/services-view.html#L96) to not only show when there are no catalog items at all, but to also show when there are no catalog items due to an applied filter returning no results.   Please review the corresponding services-view controller and how we set the `isEmpty` variable [here](https://github.com/openshift/origin-web-catalog/blob/master/src/components/services-view/services-view.controller.ts#L72).  We'll probably trigger the pfEmptyState-for-no-filter-results using a combination of `if ($ctrl.filterConfig.appliedFilters.length > 0 &&  $ctrl.filterConfig.resultsCount === 0` maybe wrap in an easier to read helper function.

Thanks,
Dave

**Comment by dtaylor113** [comment]
Hi @spadgett, so currently if there are no catalog items to begin with we only display a string "There are no catalog items."  -this should probably be replaced with a [pfEmptyState](https://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfEmptyState) component.  Our question is, what instructions should we display to the user when no catalog items were found?  Thinking something like "Contact your cluster administrator".   Should it be an Error icon?  Note: this is different from showing the 'no results found' empty state talked about in this PR.

**Comment by spadgett** [comment]
> Hi @spadgett, so currently if there are no catalog items to begin with we only display a string "There are no catalog items."

@dtaylor113 It's really hard to get a completely empty catalog since the installer and cluster up will add items for you. I'm not worried about that case since it's going to be extremely rare.

The more common case is typing a filter that hides everything.
